### ISSUE TITLE
HTML formatting + indentation needs additional work

### ISSUE THREAD

**Issue by ad3429** [turtlesquared/TeaCozy2#1]
https://github.com/turtlesquared/TeaCozy2/blob/master/index.html#L1-L98

You generally followed good code practices, but your indentation/formatting can be quite inconsistent at times. You should make sure your divs align accordingly so that it's easy to see where the open and close tags are located. Here is an excellent resource on indentation and formatting in general for HTML:

https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/

**Comment by turtlesquared** [comment]
Thanks for the link! I see what you mean about the inconsistent formatting. Will make sure I am more mindful in the next project.
